name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  # TAHAP INTEGRASI
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Mock Install Dependencies
        run: echo "Menginstal dependensi aplikasi..."

      - name: Run Unit Test
        run: |
          echo "Menjalankan unit test..."
          echo "Test Passed! Aplikasi aman dan berjalan normal."

  # TAHAP DELIVERY / DEPLOYMENT
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image for Staging
        run: |
          docker build -t web-devops:staging .
          echo "Docker image versi staging berhasil dibuat."

      - name: Deploy to Staging Environment
        run: |
          echo "Menghubungkan ke lingkungan staging (Simulasi Staging Server)..."
          echo "Mengunduh container baru dan memperbarui layanan..."
          echo "Deployment Sukses! Aplikasi otomatis ter-deploy ke lingkungan staging."